# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: '14-ea'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Run tests
      run: |
        git submodule update --init --recursive
        cd tests
        ./run-test 1a
        ./run-test 1b | grep 'Pass/Total: 16/17'
        # pa1b has one failing test case that is students' job.
        ./run-test 2
        ./run-test 3
        ./run-test 5-x86
